services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=mock_server_db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - API_KEY=your-secret-api-key-here
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./src:/app/src
    command: sh -c "sleep 5 && npm run migrate && npm start"

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=mock_server_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
